### ISSUE TITLE
When clock is not UTC timestamps are wrong

### ISSUE THREAD

**Issue by chasers** [Logflare/logflare_logger_backend#35]
Prevalent on my dev box ... seems to be okay on prod.

![image](https://user-images.githubusercontent.com/1019814/90018044-348fd000-dc61-11ea-82a5-7794365f9ef8.png)

**Comment by ontofractal** [comment]
Fixed de252b2b4fc95da571bb31a22dca718624d072d0

**Comment by chasers** [comment]
https://github.com/Logflare/logflare_logger_backend/releases/tag/v0.7.5
