### ISSUE TITLE
Jason.Encoder not implemented for &:gen_server.format_log/1 of type Function

### ISSUE THREAD

**Issue by chasers** [Logflare/logflare_logger_backend#36]
Some logs from customers are causing this exception on production.

(exit) an exception was raised: ** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for &:gen_server.format_log/1 of type Function

**Comment by chasers** [comment]
If you encounter this issue you can do a GET request to `https://logflare.app/sources/[ID]/clear` and it'll clear the log cache.

**Comment by ontofractal** [comment]
Fixed 04ed518a1e15527f6caa021d89303bd1255ab406

**Comment by chasers** [comment]
https://github.com/Logflare/logflare_logger_backend/releases/tag/v0.7.5
