### ISSUE TITLE
Switch to Mint and Finch

### ISSUE THREAD

**Issue by chasers** [Logflare/logflare_logger_backend#45]
Hackney's pooling isn't great. Switch to Mint via [Finch](https://github.com/keathley/finch).

Also create a common API client for LogflareLoggerBacknd and TelemetryMetricsLogflare.

**Comment by gabrielrinaldi** [comment]
I'm coming from Timber (they shutdown without any warning), and those would be really nice things to have.

**Comment by chasers** [comment]
Switching to Mint with a common API interface: https://github.com/Logflare/logflare_logger_backend/releases/tag/v0.8.0-rc.6

The new Logflare API core for Elixir projects is here: https://github.com/Logflare/logflare_api_client

And [we've begun Telemetry integration](https://github.com/Logflare/telemetry_metrics_logflare) and if anyone would like to help we'd love to work with you on it! This first release is particularly useful with telemetry_poller to get all your system metrics running through Logflare.
