### ISSUE TITLE
Crashes in remote console on some umbrella setups

### ISSUE THREAD

**Issue by chasers** [Logflare/logflare_logger_backend#54]
@chasers Everything seems to be working in prod, however I just started a remote console to my server and I'm seeing this message repeating every second or so.

```
21:43:30.877 [error] GenServer #PID<0.140.0> terminating
** (stop) {:EXIT, {%RuntimeError{message: "could not lookup Ecto repo LogflareLogger.Repo because it was not started or it does not exist"}, [{Ecto.Repo.Registry, :lookup, 1, [file: 'lib/ecto/repo/registry.ex', line: 19]}, {Ecto.Repo.Queryable, :execute, 4, [file: 'lib/ecto/repo/queryable.ex', line: 210]}, {Ecto.Repo.Queryable, :all, 3, [file: 'lib/ecto/repo/queryable.ex', line: 17]}, {LogflareLogger.BatchCache, :flush, 1, [file: 'lib/logflare_logger/batch_cache.ex', line: 44]}, {LogflareLogger.HttpBackend, :flush!, 1, [file: 'lib/logflare_logger/http_backend.ex', line: 113]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 620]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 602]}, {:gen_event, :handle_msg, 6, [file: 'gen_event.erl', line: 390]}]}}
Last message: {:gen_event_EXIT, LogflareLogger.HttpBackend, {:EXIT, {%RuntimeError{message: "could not lookup Ecto repo LogflareLogger.Repo because it was not started or it does not exist"}, [{Ecto.Repo.Registry, :lookup, 1, [file: 'lib/ecto/repo/registry.ex', line: 19]}, {Ecto.Repo.Queryable, :execute, 4, [file: 'lib/ecto/repo/queryable.ex', line: 210]}, {Ecto.Repo.Queryable, :all, 3, [file: 'lib/ecto/repo/queryable.ex', line: 17]}, {LogflareLogger.BatchCache, :flush, 1, [file: 'lib/logflare_logger/batch_cache.ex', line: 44]}, {LogflareLogger.HttpBackend, :flush!, 1, [file: 'lib/logflare_logger/http_backend.ex', line: 113]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 620]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 602]}, {:gen_event, :handle_msg, 6, [file: 'gen_event.erl', line: 390]}]}}}
21:43:31.879 [error] :gen_event handler LogflareLogger.HttpBackend installed in Logger terminating
** (RuntimeError) could not lookup Ecto repo LogflareLogger.Repo because it was not started or it does not exist
    (ecto 3.5.6) lib/ecto/repo/registry.ex:19: Ecto.Repo.Registry.lookup/1
    (ecto 3.5.6) lib/ecto/repo/queryable.ex:210: Ecto.Repo.Queryable.execute/4
    (ecto 3.5.6) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (logflare_logger_backend 0.8.0-rc.4) lib/logflare_logger/batch_cache.ex:44: LogflareLogger.BatchCache.flush/1
    (logflare_logger_backend 0.8.0-rc.4) lib/logflare_logger/http_backend.ex:113: LogflareLogger.HttpBackend.flush!/1
    (stdlib 3.13) gen_event.erl:620: :gen_event.server_update/4
    (stdlib 3.13) gen_event.erl:602: :gen_event.server_notify/4
    (stdlib 3.13) gen_event.erl:390: :gen_event.handle_msg/6
Last message: :flushed: 
```

Should I open a separate issue for this?

_Originally posted by @darksheik in https://github.com/Logflare/logflare_logger_backend/issues/51#issuecomment-772018344_

**Comment by chasers** [comment]
Please provide a repo that reproduces this or more info like:

- umbrella mix.exs
- individual app mix.exs files
- distillery rel/config.exs
- config/config.exs and individual app configs (if present)
- snippets of shell scripts that are used to run/start releases and remote consoles

**Comment by darksheik** [comment]
I made a sample umbrella app within our organization which approximates our setup and configuration pretty closely, which is that the Logflare creds are configured on the app in the umbrella which all others depend on.  I was able to produce a different error on the remote console that might be tangentially related.

https://github.com/SeatScouts/elixir-umbrella-sample-application

I've stripped our creds from the repo so you'll have to add some of your own.

Build a release using:
```
mix distillery.release
```
It should give you instructions as to how to launch a `console` and a `remote_console`.

The console started fine for me and I observed logs going out, but then I think attaching a remote_console created a tangentially related issue, which is that it can't find the configuration (eve:
```
=SUPERVISOR REPORT==== 8-Feb-2021::14:10:14.776590 ===
    supervisor: {local,'Elixir.Logger.Supervisor'}
    errorContext: start_error
    reason: {'EXIT',
                {#{'__exception__' => true,
                   '__struct__' => 'Elixir.RuntimeError',
                   message =>
                       <<"ERROR when installing backend LogflareLogger.HttpBackend: {{{:case_clause, \"Logflare source_id for LogflareLogger backend is NOT configured\"}, [{Logger.Watcher, :init, 1, [file: 'lib/logger/watcher.ex', line: 25]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 417]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 385]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}, {:child, :undefined, LogflareLogger.HttpBackend, {Logger.Watcher, :start_link, [{LogflareLogger.HttpBackend, LogflareLogger.HttpBackend}]}, :transient, 5000, :worker, [Logger.Watcher]}}">>},
                 [{'Elixir.Logger.BackendSupervisor','-start_link/1-fun-0-',
                      2,
                      [{file,"lib/logger/backend_supervisor.ex"},{line,23}]},
                  {'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,
                      [{file,"lib/enum.ex"},{line,2111}]},
                  {'Elixir.Logger.BackendSupervisor',start_link,1,
                      [{file,"lib/logger/backend_supervisor.ex"},{line,13}]},
                  {supervisor,do_start_child_i,3,
                      [{file,"supervisor.erl"},{line,385}]},
                  {supervisor,do_start_child,2,
                      [{file,"supervisor.erl"},{line,371}]},
                  {supervisor,'-start_children/2-fun-0-',3,
                      [{file,"supervisor.erl"},{line,355}]},
                  {supervisor,children_map,4,
                      [{file,"supervisor.erl"},{line,1171}]},
                  {supervisor,init_children,2,
                      [{file,"supervisor.erl"},{line,321}]}]}}
    offender: [{pid,undefined},
               {id,'Elixir.Logger.BackendSupervisor'},
               {mfargs,{'Elixir.Logger.BackendSupervisor',start_link,[[]]}},
               {restart_type,permanent},
               {shutdown,infinity},
               {child_type,supervisor}]
```

@gvaughn There is a new issue open for this.

**Comment by chasers** [comment]
@darksheik @gvaughn here's what we think is going on:

The issue that was happening either with `LogflareLogger.Repo` or `LogflareLogger` config is triggered by the incompatibility of distillery release scripts and Elixir 1.10 `Logger` integration with Erlang's `:logger` module. Distillery `remote_console`  shell script or others, like migration, starts Distillery `clean_boot` release which only starts `:kernel, :stdlib, :compiler, :elixir` applications. However, due to Elixir-Erlang's `:logger` integration, erlang `:logger`  reads Elixir's logger configuration and calls configured backend, in this instances, `LogflareLogger`. As this is `clean_boot` release, ` LogflareLogger` supervision tree is not started. There is also a bug in Elixir 1.10 where on `clean_boot` release start mix configs are not properly read. The fix for `remote_console` is in the https://github.com/Logflare/logflare-logger-umbrella-distillery-example repo. To run a fixed `remote_console` use `../../release remote_console_no_crash` shell command.
The relevant part of the fix is the `--erl "-kernel logger_level none"` option which disables the erlang `:logger` and its' integration with Elixir Logger, thus preventing crashes.

It's not possible to override distillery command scripts, we'd strongly recommend to migrate to native Elixir releases and also to Elixir 1.11 which fixes a bugs with loading of Elixir.

**Comment by chasers** [comment]
Closing for now...

**Comment by gvaughn** [comment]
Thanks for digging into that @chasers ! That custom distillery command may be the perfect compromise for us. We'll give it a try.

**Comment by darksheik** [comment]
Tried out the script and it ignored the `:none` value in our repo.
```
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

warning: the level for Erlang's logger was set to :none, but Elixir's logger was set to :info. Elixir's logger value will take higher precedence
  (logger 1.10.4) lib/logger/app.ex:102: Logger.App.add_elixir_handler/2
  (logger 1.10.4) lib/logger/app.ex:26: Logger.App.start/2
  (kernel 7.0) application_master.erl:277: :application_master.start_it_old/4
```

So, same effect.  We can try upgrading to Elixir 11 next, but I have lingering questions:

- Would it be possible to detect whether the `LogflareLogger.Repo` is started before the Backend attempts to perform its tasks?  I understand that might be a lot of repetitive checks, but perhaps not too expensive.
- Why did the previous version of the backend not suffer from the same issue?

**Comment by darksheik** [comment]
I'm starting to think it's not a releases thing, and I apologize if I sent you on a goose chase there.  I'm noticing if I add `LogflareLogger.HttpBackend` to my dev configuration, it has difficulty on startup trying to log events which are at the top of the umbrella, such as alarms about low disk space on my backup drive (below).

That went away as soon as I added `:logflare_logger_backend` to `extra_applications` in my `shared`.  However, I'm still seeing it the repetitive error attempting to `:flush` on the remote console.

I notice that `LogflareLogger.Repo` is something that was newly added to the backend as of the most recent release, based on the commit date of `2021-01-29`, and this seems to be the primary issue.

```
20:22:16.730 [info] [alarm_handler: {:set, {{:disk_almost_full, '/System/Volumes/Data'}, []}}]

20:22:16.767 [error] :gen_event handler LogflareLogger.HttpBackend installed in Logger terminating
** (RuntimeError) could not lookup Ecto repo LogflareLogger.Repo because it was not started or it does not exist
    lib/ecto/repo/registry.ex:19: Ecto.Repo.Registry.lookup/1
    lib/ecto/repo/schema.ex:211: Ecto.Repo.Schema.do_insert/4
    lib/ecto/repo/schema.ex:164: Ecto.Repo.Schema.insert!/4
    lib/logflare_logger/batch_cache.ex:16: LogflareLogger.BatchCache.put/2
    lib/logflare_logger/http_backend.ex:36: LogflareLogger.HttpBackend.handle_event/2
    (stdlib 3.13) gen_event.erl:620: :gen_event.server_update/4
    (stdlib 3.13) gen_event.erl:602: :gen_event.server_notify/4
    (stdlib 3.13) gen_event.erl:604: :gen_event.server_notify/4
    (stdlib 3.13) gen_event.erl:343: :gen_event.handle_msg/6
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:info, #PID<0.7565.0>, {Logger, "[alarm_handler: {:set, {{:disk_almost_full, '/System/Volumes/Data'}, []}}]", {{2021, 2, 9}, {20, 22, 16, 730}}, [error_logger: %{tag: :info_report, type: :std_info}, gl: #PID<0.7565.0>, pid: #PID<0.7569.0>, report_cb: #Function<0.118689316/1 in :error_logger."-fun.report_to_format/1-">, time: 1612902136692071]}}
20:22:16.786 [error] GenServer #PID<0.7545.0> terminating
```

**Comment by gvaughn** [comment]
We've got `:os_mon` in our `extra_applications` to support `observer_cli`. I think that is the source of those early disk warnings

**Comment by chasers** [comment]
I appreciate the pull request. While I don't see a huge issue with checking for that process ... is there something big blocking you from upgrading to 1.11? We're pretty sure this will not be an issue after you upgrade. If you can replicate locally can you try upgrading locally and see?

**Comment by darksheik** [comment]
I can give it a shot.  We have a 5-year-old codebase and I have a feeling there will be some deprecations we'll have to deal with.  I may use our fork for a bit until I can take a look in a couple of days.   In general, we're pretty fond of the hot deploys that Distillery makes possible and would like to hang on to those if we can, so I do hope it will solve it.

**Comment by chasers** [comment]
FWIW the fundamentals of this lib aren't changing and the ingest API has been stable for quite a while now and not changing.

And aside from this issue I was ready to push this release out of the RC phase.

**Comment by darksheik** [comment]
Small update here.  Trying Elixir 11.3 in staging and the issue with the repeating error messages remains.

**Comment by chasers** [comment]
@darksheik ah yeah, sorry meant to clarify that you'd also need to move to releases. But ... I pulled in your Repo check anyways and we now have a [new release](https://github.com/Logflare/logflare_logger_backend/releases/tag/v0.8.0).

🙏

**Comment by darksheik** [comment]
Thanks!
