### ISSUE TITLE
No logs from AWS deployment, but works if ran locally

### ISSUE THREAD

**Issue by benonymus** [Logflare/logflare_logger_backend#60]
Hey,

I am trying to add the logflare_logger_backend to my project, and if I run it locally I am getting the logs in the dashboard nicely, but on the deployed instance in AWS I am not getting anything.

Am I missing some config step for the project, or in AWS maybe?

Thank you

**Comment by chasers** [comment]
Yeah can you confirm your config? Also check the AWS logs for that instance. We output stuff to stdout if there is an issue POSTing to Logflare.
